### ISSUE TITLE
Could you update GracePlot.jl to julia 1.x ?

### ISSUE THREAD

**Issue by brioglade** [ma-laforge/GracePlot.jl#2]

**Comment by ma-laforge** [comment]
It was working in September for Juila 1.0.  I will take a look at it - maybe the problem is with the newer versions of Julia.

Could you tell me which version you are using/which platform?

Thanks.

**Comment by ma-laforge** [comment]
### Update:
I just ran `GracePlot` with Julia 1.1 on Linux 18.04.1 LTS.

Everything looks fine with this configuration.

...I would still need feedback on the configuration that gives you trouble.

**Comment by ma-laforge** [comment]
Just in case:

`GracePlot.jl` does not automatically install the `Grace` application itself (it assumes it is already accessible in the system paths simply from the command `xmgrace`).

For more information on how to install, see: https://github.com/ma-laforge/HowTo/blob/master/grace/grace_install.md#Installation

Also:
If you install `xmgrace` to a different path, you can set an environment variable in your `~/.julia/config/startup.jl` file:

```
ENV["GRACEPLOT_COMMAND"] = "/home/laforge/bin/xmgrace2"
```

**Comment by brioglade** [comment]
It works fine.
Thank you!
